/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Tutorial Intro',
      id: 'intro',
    },
    {
      type: 'doc',
      label: 'Parca',
      id: 'parca',
    },
    {
      type: 'doc',
      label: 'Parca Agent',
      id: 'parca-agent',
    },
    {
      type: 'doc',
      label: 'Parca Agent Design',
      id: 'parca-agent-design',
    },
    {
      type: 'doc',
      label: 'Parca Agent Security',
      id: 'parca-agent-security-considerations',
    },
    {
      type: 'doc',
      label: 'Concepts',
      id: 'concepts',
    },
    {
      type: 'doc',
      label: 'Storage',
      id: 'storage',
    },
    {
      type: 'doc',
      label: 'Community',
      id: 'community',
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        'kubernetes',
        'openshift',
        'systemd',
        'troubleshooting-parca-agent',
      ],
    }
  ],
};
