name: Spellcheck

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - uses: rojopolis/spellcheck-github-actions@b1a70f135d603e77d2828ef5ac7557de26657d3f # 0.63.1
      name: Spellcheck
